### ISSUE TITLE
Smartthings Device Usage

### ISSUE THREAD

**Issue by ijaspley** [jonbur/smartthings#3]
Hi there,
I've finally got iBrew to install and run, and install the device handler. I've put in the IP, port and MAC address (with and without :'s) but the kettle just states that it is "on" or states "turning off" in the Smartthings app, on the IDE webpage the device states that it is not connected. Can you help me please? I'm not sure how to boil the kettle from Smartthings app or how to correctly display the temperature.

Thanks
![screen shot 2017-02-20 at 23 04 47](https://cloud.githubusercontent.com/assets/19664782/23144671/2229b742-f7c1-11e6-8cfb-5d01269f96b4.png)

**Comment by jonbur** [comment]
Apologies - I have just realised there are some hard-coded values in the device handler that are only appropriate to my install! Lines 174, 178 and 182 need to have the IP of your server...

I will fix this later when not at work

....my bad!

**Comment by ijaspley** [comment]
And line 220?

I've changed them directly to test, should the MAC address be with or
without colons?

Thanks

**Comment by ijaspley** [comment]
Smartthings IDE states that the default port is 80, I'm using 2080, please
correct me if I'm wrong

Thanks

**Comment by ijaspley** [comment]
So I changed the ip in the device handler code to my ibrew server ip but it hasn't changed anything in terms of usage. Still displaying temperature as 0 degrees and kettle state as on (or temporarily turning off - but only until I refresh)

**Comment by jonbur** [comment]
So, the IP address that is hard-coded in the device handler is the IP of your *kettle*, not the IP of the iBrew server - sorry, been a while since I looked at this!

The port number in the config is the port number that iBrew runs its webserver on, which is 2080 by default, and the IP address in the config *is* the IP of the iBrew server
 
The device handler and iBrew interact partially synchronously and partially asynchronously. When you click the on/off switch in the device it sends a HTTP request to iBrew which in turn controls the kettle. When you click refresh it also sends and HTTP request and then parses the result. Both of these commands are synchronous. It sounds like this bit is working for you?

The device handler registers a call-back in the iBrew event handler to process events generated by iBrew. This is what updates the temperature and the on/off status. This is the async bit and sounds like the bit that is not working? (Which is not surprising as this is the most fiddly bit!)

To get this working there are a couple of things to check:

- that all the hard-coded IPs (including line 220 as you say!) are set to your *kettle* IP
- that the MAC address is set to the MAC address of the interface of your machine running iBrew (should be without colons). This is critical because smart things uses this to route the incoming updates to the correct device handler
- that you start iBrew with the event handler and web server: 'ibrew dump events web'
 (without the 'events' command line action iBrew won't process events, and therefore won't update Smart Things
- With all of the above done, hit the 'kettle' button in the device handler. This will ensure that the call back is set up on iBrew (if you are watching the iBrew console you should see a long dump as the call back handler is set up.)

Hope that helps!

**Comment by ijaspley** [comment]
It really has. I just boiled the kettle from work! I saw the temperature
rising in the Smartthings app! Do you have plans for the water level
sensor? I found the ibrew water level confusing, I might try and calibrate
it with a full kettle (I think it shows grams/mls of water and mine says
-800 at the moment)

Thank you so much for your help

**Comment by jonbur** [comment]
Great! Glad it's working (and sorry for my shoddy instructions!)

So the water sensor is notoriously unreliable - I had some dialog with the maintainer or iBrew about it and he's been struggling to get sane results in iBrew. It's pretty trivial to add to smartthings, but the data will only be as good as what iBrew sees... What use case do you have in mind?

Cheers

**Comment by ijaspley** [comment]
I was thinking of a rule so that the kettle doesn't boil dry, perhaps
manual calibration, set full , set empty and do not boil if level is
between x and y or something like that (below x would be ideal but if
numbers are weird then x and y seems more reliable

**Comment by jonbur** [comment]
So the kettle seems to have pretty good built-in protection - it won't stay on without sufficient water in it (think of the case where someone manually puts kettle on without water). The issue with implementing incremental logic based protection in SmartThings is that it would only be as good as the data on how full the kettle is, which seems flaky at best

I have been using this system for c. 4 months and turn our kettle on via SmartThings every morning. On occasion, I have forgotten to fill the kettle the night before and the kettle just comes on and then goes off pretty much straight away....

**Comment by ijaspley** [comment]
Oh, mine went on last night empty but I had tried to calibrate us in ibrew,
I'll recalibrate using the smarter app and check I haven't messed it up

**Comment by jonbur** [comment]
Thanks  - please let me know

**Comment by ijaspley** [comment]
Recalibration with the smarter app did the trick, no more dry boiling

**Comment by jonbur** [comment]
Great, glad it's sorted

**Comment by jonbur** [comment]
Hi, just to say I have pushed an update of the device handler to GitHub to take the IP of the kettle as a config value: https://github.com/jonbur/SmartThingsPublic/blob/master/devicetypes/jonbur/ibrew.src
